### ISSUE TITLE
More tagged releases

### ISSUE THREAD

**Issue by PureTryOut** [andlo/fairytalez-skill#21]
Hey thanks for this skill! So far this seems to be the only skill that actually has a tagged release.
In an effort to package Mycroft and it's skills for Alpine Linux, I'd like for every skill to have tagged releases like this one.

However, it seems a couple of years have gone by since the first release of this skill, and there have been a bunch of commits soon. Could you make a new release so I can package it?

**Comment by andlo** [comment]
done
