### ISSUE TITLE
Make source configurable

### ISSUE THREAD

**Issue by denics** [andlo/fairytalez-skill#22]
Thanks for this great initiative. 

It would be nice to be able to configure the source for the tales. For example, https://www.thefablecottage.com/english proposes tales in 6 languages so that a children should be able to listen to "snow white" or "biancaneve" depending on the mood. I would love to contribute, but I am a real noob in python and making your code "configurable" requires a bit of structural change (I am looking at the NPR news skill as example)

**Comment by andlo** [comment]
Yah That woudl be a nice feature.

Yhis skill do however use scraping a website to get the stories and that is made specific for that site. But I do have other sites with stories in different languages. Look at
https://github.com/andlo/hcandersen-skill and I have another not finosh Grimm skill ;)

**Comment by andlo** [comment]
This skill is not working anymore.

Have a look at https://github.com/andlo/ovos-skill-fairytales

**Comment by andlo** [comment]
.
