### ISSUE TITLE
your skill is crashing mycroft clients

### ISSUE THREAD

**Issue by geetee24** [andlo/fairytalez-skill#26]
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 67765: ordinal not in range(256)

please fix your content on 
        "description": "This skill enables Mycroft to tell lots of fairytales. So make a cup of coco, and sit back and enjoy listning to the good tales.\n\nContent is from fairytalez.com, so please go visit there if you like the stories.\nFairytalez.com is the world's largest collection of fairy tales, fables and folktales. Discover more than 2,000 classic tales plus new stories by fairy tale fans.\n\nhttp://www.fairytalez.com\n\n\n_\u201cIf you want your children to be intelligent, read them fairy tales. If you want them to be more\nintelligent, read them more fairy tales.\u201d\nAlbert Einstein_",

see the invalid 201c and d
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 67765: ordinal not in range(256)

**Comment by krisgesling** [comment]
Hey there, can you post the logs that lead up to this error too? 

I'm assuming this is on your Picroft?

**Comment by geetee24** [comment]
no logs.   simply the mc-core locks up due to the invalid chars in the
json.  its in requests....  lib

**Comment by andlo** [comment]
This skill is not working anymore.

Have a look at https://github.com/andlo/ovos-skill-fairytales
